name: Deploy to Heroku
description: Deploy docker image to heroku
inputs:
  baseImage:
    required: true
  mode:
    required: true
  herokuToken:
    required: true
runs:
  using: composite
  steps:
    - run: |
        declare -A modesToApps=( ["production"]="prod-website" ["staged"]="staged-website" )
        mode="${{ inputs.mode }}"
        app="${modesToApps[$mode]}"
        echo "Publishing to '$app'"

        if [[ "$app" == "" ]]; then exit 1 ; fi

        docker login --username=_ --password=${{ inputs.herokuToken }} registry.heroku.com
        docker tag "${{ inputs.baseImage }}" "registry.heroku.com/$app/web"
        docker push "registry.heroku.com/$app/web"

        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version
        heroku container:release -a "$app" web
      shell: bash
      env:
        HEROKU_API_KEY: ${{ inputs.herokuToken }}
