# Runs the E2E Tests
#
# Apart of `e2e/docker-compose.yml` that is in charge of running all the e2e tests

# https://github.com/cypress-io/cypress-docker-images/tree/master/included
FROM cypress/included:7.7.0 
