name: Pull Image to GitHub
description: Get an image from github
inputs:
  image:
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
        docker pull ${{ inputs.image }}
      shell: bash
