name: Run Checks
description: Lint, test, build, check formatting, etc
inputs:
  mode:
    required: true
runs:
  using: composite
  steps:
    - run: yarn prettier
      shell: bash
    - run: yarn lint:no-fix
      shell: bash
    - run: yarn test
      shell: bash
    - run: |
        if [[ "${{ inputs.mode }}" == "prod" ]]; then
          yarn vite build
        else
          yarn vite build --mode staged
        fi
      shell: bash
    - run: yarn test:e2e
      shell: bash
