name: Run Checks
description: Lint, test, build, check formatting, etc
inputs:
  npmAuthToken:
    required: true
runs:
  using: composite
  steps:
    - run: pnpm format:check
      shell: bash
    - run: pnpm lint:no-fix
      shell: bash
    - run: pnpm test
      shell: bash
    - run: pnpm build:docker
      shell: bash
      env:
        GITHUB_PACKAGES_TOKEN: ${{ inputs.npmAuthToken }}
    - run: pnpm test:e2e
      shell: bash
