name: Run Checks
description: Lint, test, build, check formatting, etc
inputs:
  npmAuthToken:
    required: true
runs:
  using: composite
  steps:
    - run: yarn prettier
      shell: bash
    - run: yarn lint:no-fix
      shell: bash
    - run: yarn test
      shell: bash
    - run: yarn build:docker
      shell: bash
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npmAuthToken }}
    - run: yarn e2e
      shell: bash
