name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy_check:
    name: Check if deploy is needed
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_TYPE: ${{ steps.deploy_check.outputs.DEPLOY_TYPE }}
    steps:
      - uses: actions/checkout@v1
      - name: Deploy Check
        id: deploy_check
        run: bash .github/deploy-to-heroku.sh ${{ steps.step_one.outputs.FOO }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    needs: deploy_check
    if: needs.deploy_check.outputs.DEPLOY_TYPE != 'none'
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          yarn install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - run: |
          yarn build
      - run: |
          yarn lint
      # - run: |
      #     yarn test:unit

  prod_deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs:
      - deploy_check
      - verify
    if: needs.deploy_check.outputs.DEPLOY_TYPE == 'prod'
    steps:
      - uses: actions/checkout@v1
      - name: Setup GitHub Packages access
        run: |
          echo -e "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          cat .npmrc
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - run: |
          yarn push-dir --dir=dist --remote="https://heroku:$HEROKU_API_KEY@git.heroku.com/anime-skip-web.git" --branch=HEAD:master --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
