name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      mode:
        description: Environment (staged or prod)
        required: true
        default: staged

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-20.04
    outputs:
      imageToDeploy: ${{ steps.build-image.outputs.image }}
      tagToDeploy: ${{ steps.build-image.outputs.image }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com
          scope: '@anime-skip'
      - uses: actions/checkout@v2
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node12-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
      - uses: ./.github/actions/build-image
        id: build-image
        with:
          mode: ${{ github.event.inputs.mode }}
          npmAuthToken: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - uses: ./.github/actions/publish-image-to-github
        with:
          image: '${{ steps.build-image.outputs.image }}'
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build_image
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pull-image-from-github
        with:
          image: '${{ needs.build_image.outputs.imageToDeploy }}'
      - uses: ./.github/actions/deploy-to-heroku
        with:
          baseImage: '${{ needs.build_image.outputs.imageToDeploy }}'
          mode: '${{ github.event.inputs.mode }}'
          herokuToken: ${{ secrets.HEROKU_API_KEY }}
