name: Dev Release
on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - run: yarn prettier
      - run: yarn lint:no-fix
      - run: yarn build
      - run: yarn test
      - name: Run docker build
        run: docker build --build-arg GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN} .
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}

  push_to_registry:
    name: Push dev image
    runs-on: ubuntu-20.04
    needs: [verify]
    steps:
      - uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: anime-skip/web/website
          tags: dev
          build_args: GITHUB_PACKAGES_TOKEN=${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
