name: Prod Release
on:
  push:
    tags:
      - v*

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - run: yarn build
      - run: yarn lint
      # - run: yarn test:unit
      - name: Run docker build
        run: docker build --build-arg GITHUB_PACKAGES_TOKEN=${GITHUB_PACKAGES_TOKEN} .
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}

  prod_deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: 'v(.*)'
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: anime-skip/web/website
          tags: prod, ${{ steps.tagName.outputs.tag }}
          build_args: GITHUB_PACKAGES_TOKEN=${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - name: Deploy web
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: anime-skip-web
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_build_args: GITHUB_PACKAGES_TOKEN
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
