name: PR Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@anime-skip'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          npmAuthToken: ${{ secrets.ANIME_SKIP_PACKAGES_TOKEN }}
      - name: Run checks
        uses: ./.github/actions/run-checks
        with:
          mode: prod
