name: Verify PR
on:
  push:
    branches-ignore:
      - master

jobs:
  install:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn lint
#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/setup-node@v1
#       - uses: actions/checkout@v1
#       - run: yarn install
#       - run: yarn test:unit

#   e2e:
#     name: E2E Tests
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - uses: actions/setup-node@v1
#       - uses: actions/checkout@v1
#       - run: yarn install
#         run: yarn test:e2e
